name: Build and Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Fetch Sources
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Distribution
        run: ./gradlew dist
