name: Build and Publish
on:
  push:
    branches: [ master ]
    
permissions:
    pages: write
    id-token: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          
      - name: Build Kotlin/JS project
        run: ./gradlew :webApp:jsBrowserWebpack
      
      - name: Upload website artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: webApp/build/dist/js/productionExecutable
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
